name: Pro Tests

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 */2 * *"

jobs:
  real-archive-tests:
    # Do not change to newer releases as "fips" may not be available there.
    runs-on: ubuntu-20.04
    name: Real Archive Tests
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Run real archive tests
        env:
          PRO_TOKEN: ${{ secrets.PRO_TOKEN }}
        run: |
          set -ex

          detach() {
            sudo pro detach --assume-yes || true
            sudo rm -f /etc/apt/auth.conf.d/90ubuntu-advantage
          }
          trap detach EXIT

          # Attach pro token and enable services
          sudo pro attach ${PRO_TOKEN} --no-auto-enable

          # Cannot enable fips and fips-updates at the same time.
          # Hack: enable fips, copy the credentials and then after enabling
          # other services, add the credentials back.
          sudo pro enable fips --assume-yes
          sudo cp /etc/apt/auth.conf.d/90ubuntu-advantage /etc/apt/auth.conf.d/90ubuntu-advantage.fips-creds
          # This will disable the fips service.
          sudo pro enable fips-updates esm-apps esm-infra --assume-yes
          # Add the fips credentials back.
          sudo sh -c 'cat /etc/apt/auth.conf.d/90ubuntu-advantage.fips-creds >> /etc/apt/auth.conf.d/90ubuntu-advantage'
          sudo rm /etc/apt/auth.conf.d/90ubuntu-advantage.fips-creds

          # Make apt credentials accessible to USER.
          sudo setfacl -m u:$USER:r /etc/apt/auth.conf.d/90ubuntu-advantage

          # Run tests on Pro real archives.
          go test ./internal/archive/ --real-pro-archive

  spread-tests:
    name: Spread tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: snapcore/spread
          path: _spread

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'

      - name: Build and run spread
        env:
          PRO_TOKEN: ${{ secrets.PRO_TOKEN }}
        run: |
          (cd _spread/cmd/spread && go build)
          _spread/cmd/spread/spread -v tests/pro-archives
